### PR TITLE
Fixes for v8

### PR DESCRIPTION
**Pull request by stefankip**
Fixes for v8; using $sce to trust html and fix DI naming

### CODE REVIEW

**Comment by shumbertson** [comment]
Hello Stefan - Im out on vacation this week but will review next week.

**Comment by stefankip** [comment]
No problem!

**Review by shumbertson — CHANGES_REQUESTED** [review]
@stefankip I had a chance to look at it.  Looks like line 7 in 'informativeLabel.html' will need to be updated.  When testing in an Umbraco 8 site, I had to update that line to use the directive 'ng-bind-html='body'' instead of 'ng-bind-html-unsafe='body'' in order to get the rte content to render.

**Comment by stefankip** [comment]
Darn you're right, forgot to commit that change. Will do so on Monday.

**Review by shumbertson — APPROVED** [review]

**Pull request merged**
